[project]
name = "virel"
version = "0.1.0"
description = "A clone of a specific bot."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "discord-py",
    "jishaku",
    "psutil>=7.2.2",
    "python-dotenv>=1.2.2",
    "redis>=7.4.0",
    "orjson",
    "litestar[standard]>=2.0.0",
]

[tool.uv.sources]
discord-py = { git = "https://github.com/Rapptz/discord.py" }
jishaku = { git = "https://github.com/scarletcafe/jishaku" }
